language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
  - 1.40.0
os:
  - linux
  - osx
env:
  - CARGO_FLAGS=
before_install:
  - [[ -v WASM ]] && curl https://wasmtime.dev/install.sh -sSf | bash;
script:
  - cargo test --verbose $CARGO_FLAGS
jobs:
  include:
    - rust: 1.40.0
      os: linux
      env: WASM=1 CARGO_FLAGS="--target wasm32-wasi"
    - rust: nightly
      os: linux
      env: WASM=1 CARGO_FLAGS="--target wasm32-wasi --features nightly"
